import argparse
import logging
from typing import Dict, List, Tuple, Any

from pyspark.sql import SparkSession, functions as F

# ------------------------------------------------------------------------------
# Logger Configuration
# ------------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("LoadConfirmation_Validator")

# ------------------------------------------------------------------------------
# Contract generated by extract_load_confirmation_by_source.py
# ------------------------------------------------------------------------------
FIELDS = [
    "source_file",
    "source_system",
    "broker_name",
    "broker_phone",
    "broker_fax",
    "broker_address",
    "broker_city",
    "broker_state",
    "broker_zipcode",
    "broker_email",
    "loadConfirmationNumber",
    "totalCarrierPay",
    "carrier_name",
    "carrier_mc",
    "carrier_dot",
    "carrier_address",
    "carrier_city",
    "carrier_state",
    "carrier_zipcode",
    "carrier_phone",
    "carrier_fax",
    "carrier_contact",
    "carrier_email",
    *[
        f"{p}_{i}"
        for p in [
            "pickup_customer",
            "pickup_address",
            "pickup_city",
            "pickup_state",
            "pickup_zipcode",
            "pickup_start_datetime",
            "pickup_end_datetime",
            "pickup_reference",
            "pickup_phone",
        ]
        for i in range(1, 4)
    ],
    *[
        f"{p}_{i}"
        for p in [
            "delivery_customer",
            "delivery_address",
            "delivery_city",
            "delivery_state",
            "delivery_zipcode",
            "delivery_start_datetime",
            "delivery_end_datetime",
            "delivery_reference",
            "delivery_phone",
        ]
        for i in range(1, 4)
    ],
    "processed_at",
    "source",
]

# ------------------------------------------------------------------------------
# Ground truth records
# ------------------------------------------------------------------------------
# UTB keeps the original strict baseline.
# CY was updated to validate the real row shape shared for load 29740547.
# For CY, fields currently polluted by long OCR/text extraction are validated with
# contains/not_empty rules instead of ideal exact values.
GROUND_TRUTH: Dict[str, Dict[str, str]] = {
    "UTB": {
        "source_file": "dbfs:/Volumes/logistics/bronze/raw/txt/source=UTB/1637351047899_UTB%20ME-FL-FL.txt",
        "source": "UTB",
        "source_system": "UTB",
        "broker_name": "USA Truck Brokers Inc.",
        "broker_phone": "305-819-3000",
        "broker_fax": "305-819-7146",
        "broker_address": "14750 NW 77 Court Suite 200",
        "broker_city": "Miami Lakes",
        "broker_state": "FL",
        "broker_zipcode": "33016",
        "broker_email": "accounting@usatruckbrokers.com; talzate@usatruckbrokers.com",
        "loadConfirmationNumber": "301238",
        "totalCarrierPay": "3800.00",
        "carrier_name": "GTT FREIGHT CORP LLC",
        "carrier_mc": "1311415",
        "carrier_dot": "",
        "carrier_address": "120 9th st #1126",
        "carrier_city": "SAN ANTONIO",
        "carrier_state": "TX",
        "carrier_zipcode": "78215",
        "carrier_phone": "786-796-0858",
        "carrier_fax": "",
        "carrier_contact": "Alejandro Arboleda (dispatcher",
        "carrier_email": "",
        "pickup_customer_1": "DINGLEY PRESS LEWISTON",
        "pickup_address_1": "40 WESTMINSTER ST",
        "pickup_city_1": "LEWISTON",
        "pickup_state_1": "ME",
        "pickup_zipcode_1": "04240",
        "pickup_start_datetime_1": "2021-11-19T08:00:00",
        "pickup_end_datetime_1": "2021-11-19T23:00:00",
        "delivery_customer_1": "YBOR",
        "delivery_customer_2": "WEST PALM BEACH P&DC",
        "delivery_address_1": "1801 GRANT ST",
        "delivery_address_2": "3200 Summit Blvd",
        "delivery_city_1": "TAMPA",
        "delivery_city_2": "WEST PALM BEACH",
        "delivery_state_1": "FL",
        "delivery_state_2": "FL",
        "delivery_zipcode_1": "33605",
        "delivery_zipcode_2": "33406",
        "delivery_start_datetime_1": "2021-11-21T12:00:00",
        "delivery_start_datetime_2": "2021-11-21T19:00:00",
        "delivery_end_datetime_1": "2021-11-21T12:00:00",
        "delivery_end_datetime_2": "2021-11-21T19:00:00",
    },
    "CY": {
        "source_file": "dbfs:/Volumes/logistics/bronze/raw/txt/source=CY/1692880197737_CY%20FL-GA.txt",
        "source": "CY",
        "source_system": "CY",
        "broker_name": "Coyote Logistics, LLC",
        "broker_phone": "+1 (352) 873 3580",
        "broker_fax": "+1 (773) 365 4256",
        "broker_address": "960 Northpoint Parkway Suite 150",
        "broker_city": "Alpharetta",
        "broker_state": "GA",
        "broker_zipcode": "30005",
        "broker_email": "CarrierInvoices@coyote.com",
        "loadConfirmationNumber": "29740547",
        "totalCarrierPay": "800.00",
        "carrier_name": "GTT Freight Corp",
        "carrier_mc": "",
        "carrier_dot": "3723304",
        "carrier_address": "",
        "carrier_city": "",
        "carrier_state": "",
        "carrier_zipcode": "",
        "carrier_contact": "",
        "carrier_email": "gtt.expresscorp@gmail.com",
        "pickup_reference_1": "TO000137249",
        "delivery_reference_1": "TO000137249",
        "delivery_reference_2": "TO000137204",
        "delivery_reference_3": "TO000137217",
    },
}

for record in GROUND_TRUTH.values():
    for field_name in FIELDS:
        record.setdefault(field_name, "")

# ------------------------------------------------------------------------------
# Validation policy
# ------------------------------------------------------------------------------
# exact: direct equality after normalization.
# contains: expected token must be present in the actual value after normalization.
# not_empty: actual value must not be null/empty.
VALIDATION_POLICY: Dict[str, Dict[str, Dict[str, str]]] = {
    "UTB": {
        "exact": {
            k: v for k, v in GROUND_TRUTH["UTB"].items() if k not in {"processed_at"}
        },
        "contains": {},
        "not_empty": {},
    },
    "CY": {
        "exact": {
            "source_file": GROUND_TRUTH["CY"]["source_file"],
            "source": "CY",
            "source_system": "CY",
            "broker_name": "Coyote Logistics, LLC",
            "broker_phone": "+1 (352) 873 3580",
            "broker_fax": "+1 (773) 365 4256",
            "broker_address": "960 Northpoint Parkway Suite 150",
            "broker_city": "Alpharetta",
            "broker_state": "GA",
            "broker_zipcode": "30005",
            "broker_email": "CarrierInvoices@coyote.com",
            "loadConfirmationNumber": "29740547",
            "totalCarrierPay": "800.00",
            "carrier_name": "GTT Freight Corp",
            "carrier_mc": "",
            "carrier_dot": "3723304",
            "carrier_address": "",
            "carrier_city": "",
            "carrier_state": "",
            "carrier_zipcode": "",
            "carrier_contact": "",
            "carrier_email": "gtt.expresscorp@gmail.com",
            "pickup_reference_1": "TO000137249",
            "delivery_reference_1": "TO000137249",
            "delivery_reference_2": "TO000137204",
            "delivery_reference_3": "TO000137217",
        },
        "contains": {
            "pickup_customer_1": "Ocala 3PL 9001",
            "delivery_customer_1": "American Freight Store 29",
            "delivery_customer_2": "American Freight Store 129",
            "delivery_customer_3": "American Freight Store 9111",
        },
        "not_empty": {
            "processed_at": "processed_at must be populated",
            "pickup_customer_1": "pickup_customer_1 must be populated",
            "pickup_address_1": "pickup_address_1 must be populated",
            "pickup_city_1": "pickup_city_1 must be populated",
            "pickup_state_1": "pickup_state_1 must be populated",
            "pickup_zipcode_1": "pickup_zipcode_1 must be populated",
            "delivery_customer_1": "delivery_customer_1 must be populated",
            "delivery_customer_2": "delivery_customer_2 must be populated",
            "delivery_customer_3": "delivery_customer_3 must be populated",
            "delivery_address_1": "delivery_address_1 must be populated",
            "delivery_address_2": "delivery_address_2 must be populated",
            "delivery_address_3": "delivery_address_3 must be populated",
            "delivery_city_1": "delivery_city_1 must be populated",
            "delivery_city_2": "delivery_city_2 must be populated",
            "delivery_city_3": "delivery_city_3 must be populated",
            "delivery_state_1": "delivery_state_1 must be populated",
            "delivery_state_2": "delivery_state_2 must be populated",
            "delivery_state_3": "delivery_state_3 must be populated",
            "delivery_zipcode_1": "delivery_zipcode_1 must be populated",
            "delivery_zipcode_2": "delivery_zipcode_2 must be populated",
            "delivery_zipcode_3": "delivery_zipcode_3 must be populated",
        },
    },
}


# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------
def normalize_value(value: Any) -> str:
    if value is None:
        return ""
    return " ".join(str(value).strip().lower().split())


def add_missing_columns(df, fields: List[str]):
    for field_name in fields:
        if field_name not in df.columns:
            logger.warning(
                "Target table does not contain column '%s'. It will be treated as NULL for validation.",
                field_name,
            )
            df = df.withColumn(field_name, F.lit(None).cast("string"))
    return df


def select_validation_columns(df, fields: List[str]):
    return df.select(*[F.col(c).cast("string").alias(c) for c in fields])


def build_validation_fields(source: str, ignore_source_file: bool) -> List[str]:
    policy = VALIDATION_POLICY[source]
    selected = (
        set(policy["exact"].keys())
        | set(policy["contains"].keys())
        | set(policy["not_empty"].keys())
    )
    if ignore_source_file:
        selected.discard("source_file")
    return [field_name for field_name in FIELDS if field_name in selected]


def compare_records(
    source: str,
    target_values: Dict[str, Any],
    validation_fields: List[str],
) -> List[Tuple[str, str, str, Any]]:
    policy = VALIDATION_POLICY[source]
    results: List[Tuple[str, str, str, Any]] = []

    for field_name in validation_fields:
        actual = target_values.get(field_name)
        normalized_actual = normalize_value(actual)

        if field_name in policy["exact"]:
            expected = policy["exact"][field_name]
            status = (
                "✅ Match"
                if normalize_value(expected) == normalized_actual
                else "❌ Mismatch"
            )
            results.append((field_name, status, expected, actual))
            continue

        if field_name in policy["contains"]:
            expected = policy["contains"][field_name]
            status = (
                "✅ Contains"
                if normalize_value(expected) in normalized_actual
                else "❌ Missing token"
            )
            results.append((field_name, status, f"contains: {expected}", actual))
            continue

        if field_name in policy["not_empty"]:
            expected = policy["not_empty"][field_name]
            status = "✅ Not empty" if normalized_actual else "❌ Empty"
            results.append((field_name, status, expected, actual))

    return results


# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Load Confirmation Extractor Validator for UTB and CY"
    )
    parser.add_argument(
        "--source_table",
        required=True,
        help="Spark table name for validation. Example: logistics.bronze.truckr_loads",
    )
    parser.add_argument(
        "--source",
        required=True,
        choices=["UTB", "CY", "utb", "cy"],
        help="Source ground truth to validate: UTB or CY",
    )
    parser.add_argument(
        "--ignore_source_file",
        action="store_true",
        help="Ignore source_file comparison when the DBFS path differs by environment.",
    )
    args = parser.parse_args()

    source = args.source.upper().strip()
    source_table = args.source_table
    load_id = GROUND_TRUTH[source]["loadConfirmationNumber"]
    validation_fields = build_validation_fields(source, args.ignore_source_file)

    spark = SparkSession.builder.appName(f"{source}_Extractor_Validator").getOrCreate()
    logger.info(
        "Starting validation for source=%s, table=%s, loadConfirmationNumber=%s",
        source,
        source_table,
        load_id,
    )

    target_df = spark.table(source_table)
    target_df = add_missing_columns(
        target_df, list(set(validation_fields + ["loadConfirmationNumber", "source"]))
    )
    target_df = select_validation_columns(
        target_df,
        list(dict.fromkeys(validation_fields + ["loadConfirmationNumber", "source"])),
    )

    filtered_target = target_df.filter(
        F.col("loadConfirmationNumber") == F.lit(load_id)
    )
    if "source" in target_df.columns:
        filtered_target = filtered_target.filter(
            (F.upper(F.col("source")) == source) | F.col("source").isNull()
        )

    target_rows = filtered_target.limit(2).collect()
    results: List[Tuple[str, str, str, Any]] = []

    if not target_rows:
        logger.error(
            "No record found for source=%s, loadConfirmationNumber=%s", source, load_id
        )
        for field_name in validation_fields:
            results.append((field_name, "❌ Missing record", "record exists", None))
    else:
        if len(target_rows) > 1:
            logger.warning(
                "More than one record found for source=%s, loadConfirmationNumber=%s. Validating the first row only.",
                source,
                load_id,
            )
        logger.info(
            "Found record for source=%s, loadConfirmationNumber=%s", source, load_id
        )
        target_values = target_rows[0].asDict()
        results = compare_records(source, target_values, validation_fields)

    logger.info(
        "Validation results for source=%s, loadConfirmationNumber=%s:", source, load_id
    )
    for field_name, status, expected, actual in results:
        line = (
            f"{field_name:35} | {status:16} | expected='{expected}' | actual='{actual}'"
        )
        if status.startswith("✅"):
            logger.info(line)
        else:
            logger.error(line)

    errors = [r for r in results if r[1].startswith("❌")]
    if errors:
        logger.error(
            "Validation failed for source=%s. Error count=%s", source, len(errors)
        )
        for field_name, status, expected, actual in errors:
            logger.error("  - %s: expected='%s' got='%s'", field_name, expected, actual)
        raise ValueError(
            f"Validation failed for source={source}. Error count={len(errors)}"
        )

    logger.info(
        "✅ All validation rules passed for source=%s, loadConfirmationNumber=%s.",
        source,
        load_id,
    )


if _name_ == "_main_":
    main()
    logger.info("✅ All fields match perfectly.")
